sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps=""

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low"

services:
  - mongodb

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable; fi
  - if [ "$deps" = "" ]; then composer install; fi

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
