sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - deps=""

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low"

services:
  - mongodb

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer require 'phpunit/phpunit:^4.8.35|^5.4.3|^6.0' --dev --no-update

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable; fi
  - if [ "$deps" = "" ]; then composer update; fi

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
